/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package jdesechosfabrica.Vstas.Gui.Productores;

import java.awt.Frame;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import jdesechosfabrica.Controladores.Productor.ListarProductorControlador;
import jdesechosfabrica.Controladores.Residuo.OtenerResiduoPorIdControlador;
import jdesechosfabrica.Modelo.CasosDeUso.Productor.ListarProductoresCasoDeUso;
import jdesechosfabrica.Modelo.CasosDeUso.Residuo.ObtenerResiduoPorIdCasoDeUso;
import jdesechosfabrica.Modelo.Dao.ProductorDao;
import jdesechosfabrica.Modelo.Dao.ResiduoDao;
import jdesechosfabrica.Modelo.Dto.Productor.ListarProductorResponseDto;
import jdesechosfabrica.Modelo.Dto.Productor.ProductorDto;
import jdesechosfabrica.Modelo.Dto.Residuo.ObtenerResiduoPorIdPeticionDto;
import jdesechosfabrica.Modelo.Dto.Residuo.ObtenerResiduoPorIdRespuestaDto;
import jdesechosfabrica.Vstas.Gui.Residuos.VentanaCrearResiduo;

/**
 *
 * @author HP
 */
public class VentanaListarProductor extends javax.swing.JDialog {

    private ListarProductorResponseDto response;

    /**
     * Creates new form VentanaListarProductor
     */
    public VentanaListarProductor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenu1 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buttonCancelar = new javax.swing.JButton();
        buttonAgregarResiduo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProductores = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableResiduosProductor = new javax.swing.JTable();

        jMenu1.setText("jMenu1");
        jPopupMenu2.add(jMenu1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Productores");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Productores En El Sistema");

        jLabel2.setText("Residuos del Productor");

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCancelarActionPerformed(evt);
            }
        });

        buttonAgregarResiduo.setText("Agregar Residuo");
        buttonAgregarResiduo.setToolTipText("Agregar Residuo al productor seleccionado");
        buttonAgregarResiduo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarResiduoActionPerformed(evt);
            }
        });

        jButton1.setText("Eliminar Residuo");
        jButton1.setToolTipText("Eliminar residuo seleccionado");

        tableProductores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableProductores);

        jScrollPane3.setViewportView(jScrollPane1);

        tableResiduosProductor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableResiduosProductor);

        jScrollPane4.setViewportView(jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonAgregarResiduo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonCancelar))
                    .addComponent(jScrollPane3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelar)
                    .addComponent(buttonAgregarResiduo)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAgregarResiduoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarResiduoActionPerformed
       if(tableProductores.getSelectedRow()>=0){
           ProductorDto productorSeleccionado = response.getProductores().get(tableProductores.getSelectedRow());
           VentanaCrearResiduo ventana = new VentanaCrearResiduo(
                                                                                    (Frame)this.getParent(),
                                                                                    true, 
                                                                                    productorSeleccionado);
           ventana.setLocationRelativeTo(this);
           ventana.setVisible(true);
       }
    }//GEN-LAST:event_buttonAgregarResiduoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        cargarDatosProductor();
    }//GEN-LAST:event_formWindowOpened

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void cargarDatosProductor() {
        DefaultTableModel modelProductor = new DefaultTableModel(new Object[]{
            "ID",
            "Nombre",
            "Tipo Actividad",
            "Pais",
            "Ciudad",
            "Barrio",
            "Calle",
            "Numero"
        }, 0) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        ProductorDao productorDao = new ProductorDao();
        ListarProductoresCasoDeUso casoDeUso = new ListarProductoresCasoDeUso(productorDao);
        ListarProductorControlador controlador = new ListarProductorControlador(casoDeUso);

        response = controlador.ejecutarAccion();

        for (var productorDto : response.getProductores()) {
            modelProductor.addRow(
                    new Object[]{
                        productorDto.getId(),
                        productorDto.getNombre(),
                        productorDto.getTipoActividad(),
                        productorDto.getPais(),
                        productorDto.getCiudad(),
                        productorDto.getBarrio(),
                        productorDto.getCalle(),
                        productorDto.getNumero(),}
            );
        }

        tableProductores.setModel(modelProductor);

        var selectionModel = tableProductores.getSelectionModel();

        selectionModel.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    int filaSeleccionada = tableProductores.getSelectedRow();

                    llenarTablaResiduos(response.getProductores().get(filaSeleccionada));
                }
            }

        });
    }

    private void llenarTablaResiduos(ProductorDto productor) {
        DefaultTableModel modelResiduos = new DefaultTableModel(new Object[]{
            "ID",
            "Código",
            "Tipo de Residuo",
            "Fecha de Generacion",
            "Cantidad Total Kg",
            "Hubo incidente de seguridad"
        }, 0) {

            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        try {
            ResiduoDao residuoDao = new ResiduoDao();
            ObtenerResiduoPorIdCasoDeUso casoDeUso = new ObtenerResiduoPorIdCasoDeUso(residuoDao);
            OtenerResiduoPorIdControlador controlador = new OtenerResiduoPorIdControlador(casoDeUso);

            for (var id : productor.getResiduosIds()) {
                ObtenerResiduoPorIdRespuestaDto respuesta = controlador.ejecutarAccion(new ObtenerResiduoPorIdPeticionDto(id));
                modelResiduos.addRow(new Object[]{
                    respuesta.getId(),
                    respuesta.getCodigo(),
                    respuesta.getTipoResiduo(),
                    respuesta.getFechaGeneracion(),
                    respuesta.getCantidadTotalKilos(),
                    respuesta.isHuboIncidenteSeguridad()
                });
            }

            tableResiduosProductor.setModel(modelResiduos);
        } catch (Exception error) {
            JOptionPane.showMessageDialog(this, error.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaListarProductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaListarProductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaListarProductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaListarProductor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaListarProductor dialog = new VentanaListarProductor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregarResiduo;
    private javax.swing.JButton buttonCancelar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tableProductores;
    private javax.swing.JTable tableResiduosProductor;
    // End of variables declaration//GEN-END:variables
}
