/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jdesechosfabrica.Vstas.Gui;

/**
 *
 * @author HP
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuProductores = new javax.swing.JMenu();
        menuResiduos = new javax.swing.JMenu();
        menuTraslados = new javax.swing.JMenu();
        menuTratamientoPosterior = new javax.swing.JMenu();
        menuDestino = new javax.swing.JMenu();
        menuEnvase = new javax.swing.JMenu();
        menuTransportista = new javax.swing.JMenu();
        menuConstituyenteQuimico = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuProductores.setText("Productores");
        jMenuBar1.add(menuProductores);

        menuResiduos.setText("Residuos");
        jMenuBar1.add(menuResiduos);

        menuTraslados.setText("Traslado");
        jMenuBar1.add(menuTraslados);

        menuTratamientoPosterior.setText("Tratamiento Posterior");
        jMenuBar1.add(menuTratamientoPosterior);

        menuDestino.setText("Destino");
        jMenuBar1.add(menuDestino);

        menuEnvase.setText("Envase");
        jMenuBar1.add(menuEnvase);

        menuTransportista.setText("Transportista");
        jMenuBar1.add(menuTransportista);

        menuConstituyenteQuimico.setText("Constituyente Quimico");
        jMenuBar1.add(menuConstituyenteQuimico);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuConstituyenteQuimico;
    private javax.swing.JMenu menuDestino;
    private javax.swing.JMenu menuEnvase;
    private javax.swing.JMenu menuProductores;
    private javax.swing.JMenu menuResiduos;
    private javax.swing.JMenu menuTransportista;
    private javax.swing.JMenu menuTraslados;
    private javax.swing.JMenu menuTratamientoPosterior;
    // End of variables declaration//GEN-END:variables
}
